const fs = require("fs");
const path = require("path");
const acorn = require("acorn");

const ROOT = path.resolve(__dirname, "..");
const source = fs.readFileSync(path.join(ROOT, "assets/js/tempdb.js"), "utf8");
const ast = acorn.parse(source, { ecmaVersion: "latest", sourceType: "script" });
const declarations = new Map();

function walk(node) {
  if (!node || typeof node.type !== "string") return;
  if (node.type === "FunctionDeclaration" && node.id?.name) declarations.set(node.id.name, source.slice(node.start, node.end));
  for (const value of Object.values(node)) {
    if (Array.isArray(value)) value.forEach(walk);
    else if (value && typeof value.type === "string") walk(value);
  }
}

walk(ast);

const functionNames = [
  "splitDefinitions", "matchingParen", "validateDialect", "parseRelational", "findClosingBrace",
  "parseMongo", "parseRedis", "recommendRule", "hashSeed", "createRandom", "pick", "uuid",
  "allowedValues", "defaultValue", "limitText", "generateValue", "sqlIdentifier", "sqlValue",
  "formatSql", "formatMongo", "redisValue", "shellQuote", "formatRedis", "formatCsv"
];

for (const name of functionNames) {
  if (!declarations.has(name)) throw new Error(`TempDB test harness could not find ${name}()`);
}

const harness = new Function(`
  let selectedDb = "mysql";
  let currentSchema = null;
  const lang = "ko";
  ${functionNames.map((name) => declarations.get(name)).join("\n")}
  return {
    ${functionNames.join(",")},
    setDb(value) { selectedDb = value; },
    setSchema(value) { currentSchema = value; }
  };
`)();

let assertions = 0;

function assert(condition, message) {
  assertions += 1;
  if (!condition) throw new Error(message);
}

function assertColumns(result, names, label) {
  assert(result.columns.length === names.length, `${label}: expected ${names.length} columns, found ${result.columns.length}`);
  assert(JSON.stringify(result.columns.map((column) => column.name)) === JSON.stringify(names), `${label}: column order or names changed`);
}

const mysql = `CREATE TABLE app_db.accounts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(120) NOT NULL UNIQUE,
  role ENUM('admin','member','guest') NOT NULL,
  balance DECIMAL(12,2) DEFAULT 0,
  note TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;`;
const postgres = `CREATE TABLE "public"."events" (
  "id" UUID PRIMARY KEY,
  "owner_id" BIGINT NOT NULL,
  "is_public" BOOLEAN NOT NULL DEFAULT false,
  "score" NUMERIC(8,2),
  "title" VARCHAR(80) NOT NULL,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);`;
const oracle = `CREATE TABLE customers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(80) NOT NULL,
  status VARCHAR2(20) CHECK (status IN ('ACTIVE','INACTIVE')),
  credit_limit NUMBER(10,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;
const mssql = `CREATE TABLE [dbo].[orders] (
  [id] BIGINT IDENTITY(1,1) PRIMARY KEY,
  [customer_id] BIGINT NOT NULL,
  [order_no] NVARCHAR(40) NOT NULL UNIQUE,
  [is_paid] BIT NOT NULL DEFAULT 0,
  [total] DECIMAL(12,2) NOT NULL,
  [created_at] DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);`;
const mongo = `db.createCollection("profiles", {
  "validator": { "$jsonSchema": {
    "bsonType": "object",
    "required": ["email", "nickname"],
    "properties": {
      "_id": { "bsonType": "objectId" },
      "email": { "bsonType": "string", "maxLength": 120 },
      "nickname": { "bsonType": "string" },
      "tier": { "enum": ["free", "pro", "team"] },
      "created_at": { "bsonType": "date" }
    }
  }}
});`;
const redisHash = `HASH session:{id} {
  id: integer unique,
  user_id: integer required,
  token: string required unique,
  enabled: boolean required,
  created_at: datetime required
}`;
const redisJson = `JSON profile:{id} {
  id: integer unique,
  email: string required unique,
  status: enum(active|paused),
  created_at: datetime required
}`;

const relationalCases = [
  ["mysql", mysql, ["id", "email", "role", "balance", "note", "created_at"]],
  ["postgres", postgres, ["id", "owner_id", "is_public", "score", "title", "created_at"]],
  ["oracle", oracle, ["id", "full_name", "status", "credit_limit", "created_at"]],
  ["mssql", mssql, ["id", "customer_id", "order_no", "is_paid", "total", "created_at"]]
];

for (const [db, statement, columns] of relationalCases) {
  harness.setDb(db);
  assert(harness.validateDialect(statement), `${db}: representative statement should match its selected format`);
  const result = harness.parseRelational(statement);
  assertColumns(result, columns, db);
  if (/CREATE\s+TABLE\s+(?:["`\[]?[^.\s"`\]]+["`\]]?)\./i.test(statement)) {
    assert(result.table.includes("."), `${db}: schema-qualified table name should be preserved`);
  }
}

harness.setDb("mongodb");
assert(harness.validateDialect(mongo), "mongodb: validator statement should match");
const mongoResult = harness.parseMongo(mongo);
assertColumns(mongoResult, ["_id", "email", "nickname", "tier", "created_at"], "mongodb quoted JSON schema");
assert(mongoResult.columns.find((column) => column.name === "tier").type === "enum(free|pro|team)", "mongodb: enum values should be preserved");
assert(mongoResult.columns.find((column) => column.name === "email").constraints === "required", "mongodb: required fields should be detected");

harness.setDb("redis");
assert(harness.validateDialect(redisHash), "redis: HASH schema should match");
assert(harness.validateDialect(redisJson), "redis: JSON schema should match");
const redisHashResult = harness.parseRedis(redisHash);
const redisJsonResult = harness.parseRedis(redisJson);
assertColumns(redisHashResult, ["id", "user_id", "token", "enabled", "created_at"], "redis HASH");
assertColumns(redisJsonResult, ["id", "email", "status", "created_at"], "redis JSON");
assert(redisHashResult.kind === "HASH" && redisJsonResult.kind === "JSON", "redis: HASH and JSON output modes should remain distinct");

const mismatchCases = [
  ["mysql", "CREATE TABLE x (id BIGSERIAL PRIMARY KEY)"],
  ["postgres", "CREATE TABLE x (id BIGINT AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB"],
  ["oracle", "CREATE TABLE x (name NVARCHAR(20))"],
  ["mssql", "CREATE TABLE `x` (`id` BIGINT AUTO_INCREMENT)"],
  ["mongodb", "db.createCollection('x')"],
  ["redis", "CREATE TABLE x (id INT)"]
];

for (const [db, statement] of mismatchCases) {
  harness.setDb(db);
  assert(!harness.validateDialect(statement), `${db}: incompatible syntax marker should be rejected as a format mismatch`);
}

const generatorColumns = [
  { name: "id", type: "BIGINT", constraints: "PRIMARY KEY" },
  { name: "email", type: "VARCHAR(120)", constraints: "NOT NULL UNIQUE" },
  { name: "role", type: "ENUM('admin','member','guest')", constraints: "NOT NULL" },
  { name: "display_name", type: "VARCHAR(30)", constraints: "NOT NULL" },
  { name: "created_at", type: "DATETIME", constraints: "NOT NULL" }
];
const rules = ["sequence", "email", "enum", "custom", "date"];
const randomA = harness.createRandom("repeatable-seed");
const generatedA = Array.from({ length: 25 }, (_, rowIndex) => Object.fromEntries(generatorColumns.map((column, columnIndex) => [
  column.name,
  harness.generateValue({ column, rule: rules[columnIndex], customText: "테스터-{n}" }, rowIndex + 1, randomA, true, true)
])));
const randomB = harness.createRandom("repeatable-seed");
const generatedB = Array.from({ length: 25 }, (_, rowIndex) => Object.fromEntries(generatorColumns.map((column, columnIndex) => [
  column.name,
  harness.generateValue({ column, rule: rules[columnIndex], customText: "테스터-{n}" }, rowIndex + 1, randomB, true, true)
])));
assert(JSON.stringify(generatedA) === JSON.stringify(generatedB), "same seed should reproduce identical data");
assert(new Set(generatedA.map((row) => row.id)).size === 25, "sequence values should be unique");
assert(new Set(generatedA.map((row) => row.email)).size === 25, "generated email values should be unique");
assert(generatedA.every((row) => ["admin", "member", "guest"].includes(row.role)), "enum generator must stay within allowed values");
assert(generatedA[9].display_name === "테스터-10", "custom {n} placeholder should use the one-based row number");

const uniqueCustomColumn = { name: "code", type: "VARCHAR(30)", constraints: "UNIQUE NOT NULL" };
const customRandom = harness.createRandom("custom");
assert(harness.generateValue({ column: uniqueCustomColumn, rule: "custom", customText: "FIXED" }, 3, customRandom, true, false) === "FIXED-3", "unique custom text should gain a row suffix when {n} is omitted");
const requiredColumn = { name: "required_value", type: "VARCHAR(30)", constraints: "NOT NULL" };
assert(harness.generateValue({ column: requiredColumn, rule: "null", customText: "" }, 1, customRandom, true, false) !== null, "NOT NULL should be honored when constraint handling is enabled");

for (const db of ["mysql", "postgres", "oracle", "mssql"]) {
  harness.setDb(db);
  harness.setSchema({ table: db === "mssql" ? "dbo.accounts" : "app.accounts" });
  const sql = harness.formatSql(generatedA.slice(0, 3), generatorColumns);
  assert(sql.split("\n").length === 3, `${db}: SQL output should contain one INSERT per row`);
  assert(sql.includes("INSERT INTO"), `${db}: SQL output should use INSERT INTO`);
  assert(sql.includes("테스터-1"), `${db}: SQL output should preserve custom text`);
}

harness.setDb("mongodb");
harness.setSchema({ table: "profiles" });
const mongoOutput = harness.formatMongo(generatedA.slice(0, 2));
assert(mongoOutput.startsWith("db.profiles.insertMany("), "mongodb: output should use insertMany");
assert(mongoOutput.includes('"display_name": "테스터-1"'), "mongodb: generated objects should preserve column names and values");

harness.setDb("redis");
harness.setSchema(redisHashResult);
const redisHashOutput = harness.formatRedis(generatedA.slice(0, 2), generatorColumns);
assert(redisHashOutput.split("\n").every((line) => line.startsWith("HSET ")), "redis HASH: output should use HSET per row");
harness.setSchema(redisJsonResult);
const redisJsonOutput = harness.formatRedis(generatedA.slice(0, 2), generatorColumns);
assert(redisJsonOutput.split("\n").every((line) => line.startsWith("JSON.SET ")), "redis JSON: output should use JSON.SET per row");

const csv = harness.formatCsv([{ plain: "hello", quoted: "a,b", empty: null }], [
  { name: "plain" }, { name: "quoted" }, { name: "empty" }
]);
assert(csv === 'plain,quoted,empty\nhello,"a,b",', "CSV output should quote delimiters and keep NULL empty");

const sitemap = fs.readFileSync(path.join(ROOT, "dist/sitemap.xml"), "utf8");
const redirects = fs.readFileSync(path.join(ROOT, "dist/_redirects"), "utf8");
const robots = fs.readFileSync(path.join(ROOT, "dist/robots.txt"), "utf8");
const headers = fs.readFileSync(path.join(ROOT, "dist/_headers"), "utf8");
assert(sitemap.includes("https://solforge.cloud/ko/tempdb"), "sitemap should include Korean TempDB URL");
assert(sitemap.includes("https://solforge.cloud/en/tempdb"), "sitemap should include English TempDB URL");
assert(redirects.includes("/tempdb /ko/tempdb 301"), "legacy /tempdb route should redirect to Korean canonical URL");
assert(redirects.includes("/ko/tempdb/ /ko/tempdb 301"), "localized trailing slash should redirect to canonical URL");
assert(robots.includes("Sitemap: https://solforge.cloud/sitemap.xml"), "robots.txt should expose the sitemap");
assert(headers.includes("/ko/tempdb\n  Cache-Control: no-cache, no-store, must-revalidate"), "Korean TempDB HTML should opt out of stale browser caching");
assert(headers.includes("/en/tempdb\n  Cache-Control: no-cache, no-store, must-revalidate"), "English TempDB HTML should opt out of stale browser caching");

for (const language of ["ko", "en"]) {
  const html = fs.readFileSync(path.join(ROOT, `dist/${language}/tempdb.html`), "utf8");
  const expectedProductName = language === "ko" ? "DB 임시·더미 데이터 생성기" : "Database Test &amp; Dummy Data Generator";
  assert(html.includes(`rel="canonical" href="https://solforge.cloud/${language}/tempdb"`), `${language}: canonical URL missing`);
  assert(html.includes('hreflang="ko"') && html.includes('hreflang="en"') && html.includes('hreflang="x-default"'), `${language}: hreflang links missing`);
  assert(html.includes("ca-pub-1625988263075960"), `${language}: AdSense publisher code missing`);
  assert(html.includes("tempdb.js?v=20260723-3") && html.includes("tempdb.css?v=20260723-2"), `${language}: TempDB assets missing`);
  assert(!html.includes("data-i18n="), `${language}: source translation attributes should be removed from production output`);
  assert(html.includes(expectedProductName), `${language}: renamed product title missing from production page`);
  assert(!html.includes("TempDB 가짜 데이터") && !html.includes("TempDB Fake Data"), `${language}: old public product name should not remain`);
  const home = fs.readFileSync(path.join(ROOT, `dist/${language}/index.html`), "utf8");
  const features = fs.readFileSync(path.join(ROOT, `dist/${language}/features.html`), "utf8");
  assert(home.includes(`href="/${language}/tempdb"`), `${language}: homepage should link directly to TempDB`);
  assert(features.includes(`href="/${language}/tempdb"`), `${language}: features page should link directly to TempDB`);
}

const catalogSource = fs.readFileSync(path.join(ROOT, "assets/js/tool-catalog.js"), "utf8");
assert(catalogSource.includes("Database Test & Dummy Data Generator") && catalogSource.includes("DB 임시·더미 데이터 생성기"), "internal tool search should include the data generator in both languages");
for (const keyword of ["tempdb", "temp db", "임시데이터", "임시 데이터", "더미데이터", "더미 데이터", "가짜 데이터", "테스트 데이터", "mock data", "dummy data", "mysql", "postgresql", "mongodb", "oracle", "mssql", "redis"]) {
  assert(catalogSource.toLowerCase().includes(keyword), `internal tool search should match: ${keyword}`);
}
assert(source.includes("rows.slice(0, 100)"), "result preview should be capped at 100 generated rows");
assert(source.includes("generatedText = fullOutput.text"), "copy and download should retain the full generated output");

console.log(`Checked TempDB: ${assertions} assertions across 6 databases, generation formats, SEO, redirects, and ads.`);
